### ISSUE TITLE
How to run in HL2?

### ISSUE THREAD

**Issue by jtrinidad6** [sceneunderstanding-microsoft/unitysample#8]
Hello,

I have an issue with the sample project running in HoloLens2. I was able to deploy it successfully and can open the application in the device. The "help" screen is showing but there are not meshes that I can see within the device.

P.S I tried running it in unity and it works great.

**Comment by SzymonSPS** [comment]
Can you check if the "run on device" box is checked? If it works in unity it means it's loading the scene from a resource and not polling using the runtime. You may need to break into the code to double check, as I've definitely seen cases with caching of properties.

If you are definitely running the device path, you should break into the code where we call IsSupported and RequestAccessAsync. This will check if either you've denied permissions, or something else is failing. I can help depending on which issue you are encountering.

**Comment by anjutyagi23** [comment]
> Hello,
> 
> I have an issue with the sample project running in HoloLens2. I was able to deploy it successfully and can open the application in the device. The "help" screen is showing but there are not meshes that I can see within the device.
> 
> P.S I tried running it in unity and it works great.

Can you please guide us, how you were able to build as I am getting compile errors of reference missing error in all SceneUnderstanding scripts:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/47684824/87490106-ca105380-c612-11ea-9a96-37ab3906084c.png)

**Comment by jtrinidad6** [comment]
> Can you check if the "run on device" box is checked? If it works in unity it means it's loading the scene from a resource and not polling using the runtime. You may need to break into the code to double check, as I've definitely seen cases with caching of properties.
> 
> If you are definitely running the device path, you should break into the code where we call IsSupported and RequestAccessAsync. This will check if either you've denied permissions, or something else is failing. I can help depending on which issue you are encountering.

Hello, I was able to run the sample project by building it in ARM64. I was previously deploying it using ARM.

Can you provide details on how the "save data" feature works? where is it save? I can't find it anywhere in the file explorer in the device.

**Comment by SzymonSPS** [comment]
You should be able to find these in your app folder local state.

E.g. User Folders\LocalAppData\SceneUnderstanding_...\LocalState\

**Comment by jtrinidad6** [comment]
Got it. Thanks!
